### ISSUE TITLE
ReactionRoles.js

### ISSUE THREAD

**Issue by LangkaWS** [LangkaWS/Blanco#2]
#TODO

- [x] Modify menu message to add new roles or remove roles
- [ ] If create a menu when one already exists, delete former menu
- [ ] Creation in DM
